analyzer:
  errors:
    file_names: ignore
    lines_longer_than_80_chars: ignore
    one_member_abstracts: ignore
include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
