name: sentinal
description: Credit card validator
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  advanced_salomon_bottom_bar: ^3.3.4
  auto_route: ^9.2.2
  bloc: ^8.1.3
  csc_picker_plus: ^0.0.2
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  equatable: ^2.0.6
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.1
  flutter_bloc: ^8.1.4
  flutter_gen: ^5.8.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.15
  fpdart: ^1.1.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^8.0.2
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  line_icons: ^2.0.3
  lottie: ^3.1.3
  path_provider: ^2.1.5
  u_credit_card: ^1.4.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.6
  build_runner: ^2.4.13
  drift_dev: ^2.21.0
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  mockito: ^5.4.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo/
    - assets/animations/

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true
  output: lib/gen/

scripts:
  build: fvm flutter build web --dart-define=FLAVOR=stage
  build-prod: fvm flutter build web --dart-define=FLAVOR=prod
  test: fvm flutter test
  clean: fvm flutter clean
  generate: dart run build_runner build --delete-conflicting-outputs
  clean-generate: fvm flutter clean && fvm flutter pub get && dart run
    build_runner build --delete-conflicting-outputs
